import { Spa } from '@/types/spa';

export const spaData: Spa[] = [
  {
    id: 'the-falls-spa-at-lodore-falls-hotel',
    name: 'The Falls Spa at Lodore Falls Hotel',
    location: 'Borrowdale',
    websiteUrl: 'https://lakedistrictspa.co.uk',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with room, day passes £60-160 approx',
    imageUrl: '/spa-the-falls-spa-at-lodore-falls-hotel.jpg',
    keyFeatures: [
      'Spa included with room, day passes £60-160 approx',
      'Award: One of Lake District\'s finest',
      '16m outdoor hydrotherapy pool',
      '5 luxury treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Glass-walled with panoramic views, 85°C' },
      { name: 'Laconium', details: '35°C gentle heat' },
      { name: 'Salt Steam Room', details: '40°C at 95% humidity' },
      { name: 'Ice Room', details: 'Cold drench bucket' },
      { name: 'Experience Showers', details: 'Hot shower' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '16m outdoor hydrotherapy' },
      { name: 'Outdoor Pool', details: '16m hydrotherapy' },
      { name: 'Hydrotherapy Pool', details: '16m outdoor with neck jets, underwater bubble loungers' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: £60-160 approx',
      'Pre-booking: recommended',
      'Age restriction: 18+ only',
      'Spa hours: 10am-4pm thermal suite',
    ],
    goodToKnow: [
      'What to bring: Swimming attire, flip flops',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: true,
      poolOver15m: true,
      thermalSuite: true,
    },
  },
  {
    id: 'armathwaite-hall-hotel-spa',
    name: 'Armathwaite Hall Hotel & Spa',
    location: 'Bassenthwaite',
    websiteUrl: 'https://armathwaite-hall.com',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with room, day passes Packages available',
    imageUrl: '/spa-armathwaite-hall-hotel-spa.jpg',
    keyFeatures: [
      'Spa included with room, day passes Packages available',
      'Award: Celebrated spa in Lake District',
      'Multiple treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
      { name: 'Crystal Steam Room', details: 'Amethyst Crystal Cave steam room' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Indoor swimming pool' },
      { name: 'Outdoor Pool', details: 'Multiple outdoor infinity pools' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Packages available',
      'Pre-booking: Recommended',
      'Age restriction: Adults only',
      'Spa hours: Spa days available',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'brimstone-spa-at-brimstone-hotel',
    name: 'Brimstone Spa (at Brimstone Hotel)',
    location: 'Great Langdale',
    websiteUrl: 'https://brimstonehotel.co.uk',
    businessModel: 'guests-only',
    businessModelText: 'Exclusive to hotel guests only',
    imageUrl: '/spa-brimstone-spa-at-brimstone-hotel.jpg',
    keyFeatures: [
      'Exclusive to hotel guests only',
      'Award: Premium spa',
      '9m relaxation pool pool',
      'Treatment rooms available',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
      { name: 'Laconium', details: 'Gentle heat therapy' },
      { name: 'Aroma Steam Room', details: 'Aromatherapy steam room' },
      { name: 'Ice Room', details: 'Cool down experience' },
      { name: 'Experience Showers', details: 'Multi-sensory shower experience' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '9m' },
      { name: 'Outdoor Pool', details: 'Swim-through indoor/outdoor' },
      { name: 'Swim-Through Pool', details: '9m indoor/outdoor' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: Guest access automatic',
      'Age restriction: Adults only',
      'Spa hours: Throughout stay for guests',
    ],
    goodToKnow: [
      'What to bring: Provided for guests',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'spa-at-the-daffodil-hotel',
    name: 'Spa at the Daffodil Hotel',
    location: 'Grasmere',
    websiteUrl: 'https://crerarhotels.com/daffodil',
    businessModel: 'day-passes',
    businessModelText: 'Spa included with room, day passes £35 Mon-Thu, £45 Fri-Sun (3 hours)',
    imageUrl: '/spa-spa-at-the-daffodil-hotel.jpg',
    keyFeatures: [
      'Spa included with room, day passes £35 Mon-Thu, £45 Fri-Sun (3 hours)',
      'Award: Luxury experience',
      'Multiple treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Hydro pool' },
      { name: 'Hydrotherapy Pool', details: 'Hydrotherapy pool' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: £35 Mon-Thu, £45 Fri-Sun (3 hours)',
      'Pre-booking: arrive 30 mins before treatment',
      'Age restriction: 16+ only',
      'Spa hours: 8am-8pm daily, treatments 10am-6:30pm',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: false,
      poolOver15m: false,
      thermalSuite: false,
    },
  },
  {
    id: 'the-swan-hotel-spa-holte-spa',
    name: 'The Swan Hotel & Spa (Holte Spa)',
    location: 'Newby Bridge',
    websiteUrl: 'https://swanhotel.com',
    businessModel: 'day-passes',
    businessModelText: 'Spa included with room, day passes £40 (2 hours)',
    imageUrl: '/spa-the-swan-hotel-spa-holte-spa.jpg',
    keyFeatures: [
      'Spa included with room, day passes £40 (2 hours)',
      'Award: Award-winning spa',
      'Treatment rooms available',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Authentic outdoor Finnish sauna' },
      { name: 'Experience Showers', details: 'Multi-sensory shower experience' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Indoor/outdoor swim-through' },
      { name: 'Outdoor Pool', details: 'Swim-through to outdoor' },
      { name: 'Hydrotherapy Pool', details: 'Naturally filtered, minimal chlorine' },
      { name: 'Swim-Through Pool', details: 'Unique indoor-to-outdoor' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: £40 (2 hours)',
      'Pre-booking: Recommended',
      'Age restriction: 18+ (16-17 with parent/guardian)',
      'Spa hours: 10am-4pm spa access',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: false,
    },
  },
  {
    id: 'langdale-hotel-spa-langdale-leisure',
    name: 'Langdale Hotel & Spa (Langdale Leisure)',
    location: 'Ambleside',
    websiteUrl: 'https://langdale.co.uk',
    businessModel: 'hybrid',
    businessModelText: 'Free leisure facilities, premium spa upgrade available',
    imageUrl: '/spa-langdale-hotel-spa-langdale-leisure.jpg',
    keyFeatures: [
      'Free leisure facilities, premium spa upgrade available',
      'Award: Part of Langdale Estate',
      '20m indoor pool',
      'Available via Brimstone treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: '(in leisure)' },
      { name: 'Experience Showers', details: '(Tropical)' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '20m' },
      { name: 'Hot Tub', details: 'Spa bath' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: Automatic for guests',
      'Age restriction: Family leisure, 18+ for Brimstone',
      'Spa hours: Throughout stay',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: true,
      poolOver15m: true,
      thermalSuite: true,
    },
  },
  {
    id: 'the-wordsworth-hotel-spa',
    name: 'The Wordsworth Hotel & Spa',
    location: 'Grasmere',
    websiteUrl: '#',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with all room bookings',
    imageUrl: '/spa-the-wordsworth-hotel-spa.jpg',
    keyFeatures: [
      'Spa included with all room bookings',
      'Award: 4-star, 2 AA Rosettes restaurant',
      'Treatment rooms available',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Heated' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: For treatments',
      'Age restriction: Adults only for spa',
      'Spa hours: Guest access throughout stay',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: false,
    },
  },
  {
    id: 'macdonald-old-england-hotel-spa',
    name: 'Macdonald Old England Hotel & Spa',
    location: 'Bowness-on-Windermere',
    websiteUrl: 'https://macdonaldhotels.co.uk',
    businessModel: 'paid-extra',
    businessModelText: 'Spa costs extra for hotel guests',
    imageUrl: '/spa-macdonald-old-england-hotel-spa.jpg',
    keyFeatures: [
      'Spa costs extra for hotel guests',
      'Award: Established hotel',
      '20m pool',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
      { name: 'Aroma Steam Room', details: 'Aromatherapy steam room' },
      { name: 'Ice Room', details: 'Cool down experience' },
      { name: 'Experience Showers', details: 'Aromatherapy shower' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '20m with lake views' },
    ],
    accessPolicy: [
      'Hotel guest access: Must book separately/pay extra',
      'Day passes: Various packages',
      'Pre-booking: Recommended',
      'Age restriction: 18+ for treatments, kids allowed in pool',
      'Spa hours: Pool & gym 7am-6:30pm, children swim 10am-5pm',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: false,
      poolOver15m: true,
      thermalSuite: true,
    },
  },
  {
    id: 'the-spa-at-low-wood-bay',
    name: 'The Spa at Low Wood Bay',
    location: 'Windermere',
    websiteUrl: 'https://englishlakes.co.uk/low-wood-bay/spa',
    businessModel: 'paid-extra',
    businessModelText: 'Spa included with room, day passes Various packages 10am-8pm',
    imageUrl: '/spa-the-spa-at-low-wood-bay.jpg',
    keyFeatures: [
      'Spa included with all room bookings',
      'Award: Best Spa North West 2025, 5 Bubble Luxury Spa',
      'Multiple treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Fellside Sauna panoramic views' },
      { name: 'Herbal Lounge', details: 'The Herbal Lounge' },
      { name: 'Experience Showers', details: 'Multi-sensory shower experience' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Thermal & vitality pool' },
      { name: 'Outdoor Pool', details: '2x heated infinity pools' },
      { name: 'Vitality Pool', details: 'Indoor' },
      { name: 'Hot Tub', details: 'Multiple outdoor hot tubs' },
    ],
    accessPolicy: [
      'Hotel guests: 25% OFF treatments Mon-Thu only',
      'Day passes: Various packages 10am-8pm',
      'Pre-booking: advance booking recommended',
      'Age restriction: 16+ only',
      'Spa hours: Sunrise 7:30am-9:30am, Treatments 9:30am-7:30pm, Spa Days 10am-8pm',
    ],
    goodToKnow: [
      'What to bring: Own flip flops (sustainable policy)',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'ambleside-salutation-hotel-spa-waterfall-spa',
    name: 'Ambleside Salutation Hotel & Spa (Waterfall Spa)',
    location: 'Ambleside',
    websiteUrl: 'https://hotelslakedistrict.com',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with all room bookings',
    imageUrl: '/spa-ambleside-salutation-hotel-spa-waterfall-spa.jpg',
    keyFeatures: [
      'Spa included with all room bookings',
      'Award: BW Premier Collection, WorldHotels Distinctive',
      'Multiple treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
      { name: 'Ice Room', details: 'Ice fountain' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Heated' },
      { name: 'Outdoor Pool', details: 'Outdoor fountain spa' },
      { name: 'Hot Tub', details: '2x spa tubs/hot tubs' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: For treatments',
      'Age restriction: Adults only for spa',
      'Spa hours: Throughout guest stay',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: true,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'lakeside-hotel-spa',
    name: 'Lakeside Hotel & Spa',
    location: 'Newby Bridge',
    websiteUrl: 'https://lakesidehotel.co.uk',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa access varies by room type',
    imageUrl: '/spa-lakeside-hotel-spa.jpg',
    keyFeatures: [
      'Spa access varies by room type',
      '3 treatment rooms pool',
      'Call to confirm treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Steam room' },
      { name: 'Aroma Steam Room', details: '17m indoor pool' },
      { name: 'Ice Room', details: '17m with etched glass panels' },
    ],
    poolFeatures: [
      { name: 'Outdoor Pool', details: 'Poolside jacuzzi' },
      { name: 'Vitality Pool', details: 'Private relaxation area' },
      { name: 'Swim-Through Pool', details: 'Gymnasium' },
    ],
    accessPolicy: [
      'Hotel guests: Yes - Traditional sauna',
      'Day passes: Not available',
      'Spa hours: Yes - dog friendly',
    ],
    goodToKnow: [
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: false,
      poolOver15m: true,
      thermalSuite: true,
    },
  },
  {
    id: 'gilpin-hotel-lake-house',
    name: 'Gilpin Hotel & Lake House',
    location: 'Windermere',
    websiteUrl: 'https://thegilpin.co.uk',
    businessModel: 'guests-only',
    businessModelText: 'Spa access varies by room type',
    imageUrl: '/spa-gilpin-hotel-lake-house.jpg',
    keyFeatures: [
      'Spa access varies by room type',
      'Multiple rooms - Jetty Spa at Lake House pool',
      'By appointment treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Steam room' },
      { name: 'Aroma Steam Room', details: 'Heated indoor pool at Lake House (Knipe Tarn views)' },
    ],
    poolFeatures: [
      { name: 'Outdoor Pool', details: '2 outdoor hot tubs at Lake House, 22 rooms at Gilpin Hotel have private hot tubs' },
      { name: 'Vitality Pool', details: 'Vitality pool with jets' },
    ],
    accessPolicy: [
      'Hotel guests: Yes - Traditional sauna at Lake House',
      'Spa hours: Yes',
    ],
    goodToKnow: [
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: false,
      hotTub: false,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'windermere-boutique-hotel',
    name: 'Windermere Boutique Hotel',
    location: 'Windermere',
    websiteUrl: 'https://windermereboutiquehotel.co.uk',
    businessModel: 'guests-only',
    businessModelText: 'Spa access varies by room type',
    imageUrl: '/spa-windermere-boutique-hotel.jpg',
    keyFeatures: [
      'Spa access varies by room type',
      'Award: Boutique hotel with unique in-room spa concept',
      'N/A pool',
      'In-room treatments available treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Aroma Steam Room', details: 'In select suites (steam room)' },
    ],
    poolFeatures: [
      { name: 'Hot Tub', details: 'In-room hot tubs in multiple suites (outdoor & indoor options)' },
    ],
    accessPolicy: [
      'Hotel guests: Included in room rate',
      'Day passes: Not available',
      'Pre-booking: For in-room treatments',
      'Age restriction: Adults only',
      'Spa hours: N/A - in-room facilities',
    ],
    goodToKnow: [
      'What to bring: All provided in room',
    ],
    facilities: {
      sauna: false,
      steamRoom: true,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: false,
    },
  },
  {
    id: 'beech-hill-hotel-spa',
    name: 'Beech Hill Hotel & Spa',
    location: 'Windermere',
    websiteUrl: 'https://beechhillhotel.co.uk',
    businessModel: 'paid-extra',
    businessModelText: 'Spa costs extra for hotel guests',
    imageUrl: '/spa-beech-hill-hotel-spa.jpg',
    keyFeatures: [
      'Spa costs extra for hotel guests',
      'Award: Lakeside location hotel',
      '12m (40ft) indoor pool',
      'Massage/treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Sauna' },
      { name: 'Aroma Steam Room', details: 'Steam room' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '12m (40ft) indoor pool with atmospheric lighting' },
      { name: 'Outdoor Pool', details: '2 outdoor vitality spa pools' },
      { name: 'Vitality Pool', details: '2 outdoor vitality pools' },
      { name: 'Hot Tub', details: '2 outdoor hot tubs with lake views' },
    ],
    accessPolicy: [
      'Hotel guests: £20 per person (not included)',
      'Day passes: £20 per person',
      'Pre-booking: Pre-booking recommended',
      'Age restriction: Adults only for spa',
      'Spa hours: Call to confirm',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'rothay-garden-by-harbour-hotels',
    name: 'Rothay Garden by Harbour Hotels',
    location: 'Grasmere',
    websiteUrl: 'https://harbourhotels.co.uk/rothay-garden',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with room, day passes Call for pricing',
    imageUrl: '/spa-rothay-garden-by-harbour-hotels.jpg',
    keyFeatures: [
      'Spa included with room, day passes Call for pricing',
      'Award: 4 AA Silver Stars, 2 AA Rosettes restaurant',
      'N/A pool',
      '3 treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Herbal pine sauna' },
      { name: 'Aroma Steam Room', details: 'Aromatherapy room/steam room' },
      { name: 'Experience Showers', details: 'Monsoon showers' },
    ],
    poolFeatures: [
      { name: 'Hydrotherapy Pool', details: 'HydroSpa with sunken loungers' },
      { name: 'Hot Tub', details: 'Hot tub' },
    ],
    accessPolicy: [
      'Hotel guests: Likely FREE (Harbour Hotels standard)',
      'Day passes: Call for pricing',
      'Pre-booking: Pre-booking recommended',
      'Age restriction: 18+ charged as adults',
      'Spa hours: Riverside Spa - call to confirm',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'north-lakes-hotel-spa',
    name: 'North Lakes Hotel & Spa',
    location: 'Penrith',
    websiteUrl: 'https://northlakeshotel.com',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with room, day passes £15 one-off visit or £55/month membership',
    imageUrl: '/spa-north-lakes-hotel-spa.jpg',
    keyFeatures: [
      'Spa included with room, day passes £15 one-off visit or £55/month membership',
      'Award: Award-winning spa',
      '13m pool',
      'Treatment rooms available',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Single-sex saunas' },
      { name: 'Aroma Steam Room', details: 'Steam room' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '13m long pool' },
      { name: 'Hot Tub', details: 'Hot tub/whirlpool' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: £15 one-off visit or £55/month membership',
      'Pre-booking: Free for hotel residents & treatment bookings',
      'Age restriction: All ages welcome',
      'Spa hours: Classes available, aqua aerobics',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'whitewater-hotel-leisure-club',
    name: 'Whitewater Hotel & Leisure Club',
    location: 'Backbarrow',
    websiteUrl: 'https://whitewater-hotel.co.uk',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with all room bookings',
    imageUrl: '/spa-whitewater-hotel-leisure-club.jpg',
    keyFeatures: [
      'Spa included with all room bookings',
      'Award: Tripadvisor Travellers\' Choice Award 2023',
      'Range of Elemis treatments treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Sauna' },
      { name: 'Aroma Steam Room', details: 'Arabian steam room' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Heated indoor swimming pool' },
      { name: 'Hot Tub', details: 'Whirlpool/Jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: Spa treatments pre-booking recommended',
      'Age restriction: All ages welcome',
      'Spa hours: 7am-8pm (varies)',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'another-place-the-lake',
    name: 'Another Place, The Lake',
    location: 'Ullswater',
    websiteUrl: 'https://another.place/the-lake',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with room, day passes Membership available for non-guests',
    imageUrl: '/spa-another-place-the-lake.jpg',
    keyFeatures: [
      'Spa included with all room bookings',
      'Award: Contemporary lakeside retreat',
      '20m pool',
      'Swim Club includes treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Sauna' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '20m indoor pool with lake view' },
      { name: 'Hot Tub', details: 'Hot tub' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Membership available for non-guests',
      'Pre-booking: Pre-booking recommended',
      'Age restriction: Children not permitted in pool before 9am or after 6pm',
      'Spa hours: 7am-9pm daily',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: true,
      poolOver15m: true,
      thermalSuite: false,
    },
  },
  {
    id: 'castle-green-hotel',
    name: 'Castle Green Hotel',
    location: 'Kendal',
    websiteUrl: 'https://castlegreenhotel.co.uk',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with all room bookings',
    imageUrl: '/spa-castle-green-hotel.jpg',
    keyFeatures: [
      'Spa included with all room bookings',
      'Award: BW Premier Collection',
      'Small pool pool',
      'Treatment rooms available',
    ],
    thermalFacilities: [
      { name: 'Aroma Steam Room', details: 'Steam room' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Indoor pool' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: Lane swimming must be pre-booked Mon-Fri',
      'Age restriction: 16+ for gym facilities',
      'Spa hours: Pool: Mon-Fri 6:30-9:30am & 5-7pm (pre-book), Weekends no booking',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: false,
      steamRoom: true,
      iceRoom: false,
      hotTub: false,
      poolOver15m: false,
      thermalSuite: false,
    },
  },
  {
    id: 'appleby-manor-hotel-garden-spa',
    name: 'Appleby Manor Hotel & Garden Spa',
    location: 'Appleby-in-Westmorland',
    websiteUrl: 'https://applebymanor.co.uk',
    businessModel: 'paid-extra',
    businessModelText: 'Spa costs extra for hotel guests',
    imageUrl: '/spa-appleby-manor-hotel-garden-spa.jpg',
    keyFeatures: [
      'Spa costs extra for hotel guests',
      'Award: AA Rosette restaurant, £1m Garden Spa',
      'N/A pool',
      '6 treatment rooms (including couples room)',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Sauna' },
      { name: 'Salt Steam Room', details: 'Salt room/salt inhalation room' },
      { name: 'Aroma Steam Room', details: 'Steam room' },
      { name: 'Ice Room', details: 'Ice fountain' },
      { name: 'Experience Showers', details: 'Experience showers' },
    ],
    poolFeatures: [
      { name: 'Hot Tub', details: '2 outdoor hot tubs in spa garden, Private hire hot tub in glass cube' },
    ],
    accessPolicy: [
      'Hotel guest access: Must pay separately',
      'Day passes: Thermal Journey packages available',
      'Pre-booking: Pre-booking essential. Smart casual dress code in restaurant',
      'Age restriction: 16+ only',
      'Spa hours: Thermal Suite 10am-5pm Mon-Thu, 9:30am-6pm Fri-Sun',
    ],
    goodToKnow: [
      'What to bring: Bring own waterproof footwear',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'netherwood-hotel-spa',
    name: 'Netherwood Hotel & Spa',
    location: 'Grange-over-Sands',
    websiteUrl: 'https://netherwood-hotel.co.uk',
    businessModel: 'paid-extra',
    businessModelText: 'Spa costs extra for hotel guests',
    imageUrl: '/spa-netherwood-hotel-spa.jpg',
    keyFeatures: [
      'Spa costs extra for hotel guests',
      'Award: Grade II listed Victorian mansion (1893)',
      'N/A - no pool pool',
      '3 treatment rooms (including couples room)',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional sauna' },
      { name: 'Salt Steam Room', details: 'Salt inhalation room' },
      { name: 'Aroma Steam Room', details: 'Aroma steam room' },
      { name: 'Ice Room', details: 'Ice fountain' },
      { name: 'Experience Showers', details: 'Monsoon shower' },
    ],
    poolFeatures: [
      { name: 'Hot Tub', details: 'Warm wooden hot tubs (outdoor)' },
    ],
    accessPolicy: [
      'Hotel guest access: Must pay separately',
      'Day passes: £20/hour per person (£10 each additional hour)',
      'Pre-booking: Must pre-book thermal suite. Towel, robe, slippers included',
      'Age restriction: Adults only',
      'Spa hours: Thermal Suite 9am-8pm. Treatments 10am-6pm',
    ],
    goodToKnow: [
      'What to bring: Swimwear',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'grange-hotel',
    name: 'Grange Hotel',
    location: 'Grange-over-Sands',
    websiteUrl: 'https://grange-hotel.co.uk',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with all room bookings',
    imageUrl: '/spa-grange-hotel.jpg',
    keyFeatures: [
      'Spa included with all room bookings',
      'Award: Built 1866, 4-star',
      'Small pool pool',
      'Body wraps, facials, pedicures, massages treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Sauna' },
      { name: 'Aroma Steam Room', details: 'Steam room' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Heated indoor pool' },
      { name: 'Hot Tub', details: 'Jacuzzi/hot tub' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: Pool/facilities open to guests & members',
      'Age restriction: All ages welcome',
      'Spa hours: 7am-8pm daily',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  }
];

export const locations = [
  'All Locations',
  'Ambleside',
  'Appleby-in-Westmorland',
  'Backbarrow',
  'Bassenthwaite',
  'Borrowdale',
  'Bowness-on-Windermere',
  'Grange-over-Sands',
  'Grasmere',
  'Great Langdale',
  'Kendal',
  'Newby Bridge',
  'Penrith',
  'Ullswater',
  'Windermere'
];

export const facilityOptions = [
  { key: 'sauna', label: 'Sauna' },
  { key: 'steamRoom', label: 'Steam Room' },
  { key: 'iceRoom', label: 'Ice Room' },
  { key: 'hotTub', label: 'Hot Tub' },
  { key: 'poolOver15m', label: 'Pool 15m+' },
  { key: 'thermalSuite', label: 'Thermal Suite' },
] as const;

