import { Spa } from '@/types/spa';

export const spaData: Spa[] = [
  {
    id: 'the-falls-spa-at-lodore-falls-hotel',
    name: 'The Falls Spa at Lodore Falls Hotel',
    location: 'Borrowdale',
    websiteUrl: 'https://lakedistrictspa.co.uk',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa access varies by room type',
    imageUrl: '/spa-the-falls-spa-at-lodore-falls-hotel.jpg',
    keyFeatures: [
      'Spa access varies by room type',
      'Award: One of Lake District\'s finest',
      '16m outdoor hydrotherapy pool',
      '5 luxury treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Glass-walled with panoramic views, 85°C' },
      { name: 'Laconium', details: '35°C gentle heat' },
      { name: 'Salt Steam Room', details: '40°C at 95% humidity' },
      { name: 'Ice Room', details: 'Cold drench bucket' },
      { name: 'Experience Showers', details: 'Hot shower' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '16m outdoor hydrotherapy' },
      { name: 'Outdoor Pool', details: '16m hydrotherapy' },
      { name: 'Hydrotherapy Pool', details: '16m outdoor with neck jets, underwater bubble loungers' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: £60-160 approx',
      'Pre-booking: recommended',
      'Age restriction: 18+ only',
      'Spa hours: 10am-4pm thermal suite',
    ],
    goodToKnow: [
      'What to bring: Swimming attire, flip flops',
      'Parking: Available',
      'Dog-friendly: Hotel yes, spa no',
      'Treatments: Elemis & Ishga products',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: true,
      poolOver15m: true,
      thermalSuite: true,
    },
  },
  {
    id: 'armathwaite-hall-hotel-spa',
    name: 'Armathwaite Hall Hotel & Spa',
    location: 'Bassenthwaite',
    websiteUrl: 'https://armathwaite-hall.com',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa access varies by room type',
    imageUrl: '/spa-armathwaite-hall-hotel-spa.jpg',
    keyFeatures: [
      'Spa access varies by room type',
      'Award: Celebrated spa in Lake District',
      'Multiple treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
      { name: 'Crystal Steam Room', details: 'Amethyst Crystal Cave steam room' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Indoor swimming pool' },
      { name: 'Outdoor Pool', details: 'Multiple outdoor infinity pools' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Packages available',
      'Pre-booking: Recommended',
      'Age restriction: Adults only',
      'Spa hours: Spa days available',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
      'Parking: FREE - ample parking',
      'Dog-friendly: Dog-friendly rooms available',
      'Treatments: Extensive menu',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'brimstone-spa-at-brimstone-hotel',
    name: 'Brimstone Spa (at Brimstone Hotel)',
    location: 'Great Langdale',
    websiteUrl: 'https://brimstonehotel.co.uk',
    businessModel: 'guests-only',
    businessModelText: 'Exclusive to hotel guests only',
    imageUrl: '/spa-brimstone-spa-at-brimstone-hotel.jpg',
    keyFeatures: [
      'Exclusive to hotel guests only',
      'Award: Premium spa',
      '9m relaxation pool pool',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
      { name: 'Laconium', details: 'Gentle heat therapy' },
      { name: 'Aroma Steam Room', details: 'Aromatherapy steam room' },
      { name: 'Ice Room', details: 'Cool down experience' },
      { name: 'Experience Showers', details: 'Multi-sensory shower experience' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '9m' },
      { name: 'Outdoor Pool', details: 'Swim-through indoor/outdoor' },
      { name: 'Swim-Through Pool', details: '9m indoor/outdoor' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: Guest access automatic',
      'Age restriction: Adults only',
      'Spa hours: Throughout stay for guests',
    ],
    goodToKnow: [
      'What to bring: Provided for guests',
      'Parking: FREE for guests',
      'Dog-friendly: Dog-friendly rooms',
      'Treatments: Pure Alchemy + Elemis',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'spa-at-the-daffodil-hotel',
    name: 'Spa at the Daffodil Hotel',
    location: 'Grasmere',
    websiteUrl: 'https://crerarhotels.com/daffodil',
    businessModel: 'day-passes',
    businessModelText: 'Spa access varies by room type',
    imageUrl: '/spa-spa-at-the-daffodil-hotel.jpg',
    keyFeatures: [
      'Spa access varies by room type',
      'Award: Luxury experience',
      'Multiple treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Hydro pool' },
      { name: 'Hydrotherapy Pool', details: 'Hydrotherapy pool' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: £35 Mon-Thu, £45 Fri-Sun (3 hours)',
      'Pre-booking: arrive 30 mins before treatment',
      'Age restriction: 16+ only',
      'Spa hours: 8am-8pm daily, treatments 10am-6:30pm',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
      'Parking: Available',
      'Dog-friendly: Dog-friendly hotel',
      'Treatments: TempleSpa products - facials, massages',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: false,
      poolOver15m: false,
      thermalSuite: false,
    },
  },
  {
    id: 'the-swan-hotel-spa-holte-spa',
    name: 'The Swan Hotel & Spa (Holte Spa)',
    location: 'Newby Bridge',
    websiteUrl: 'https://swanhotel.com',
    businessModel: 'day-passes',
    businessModelText: 'Spa access varies by room type',
    imageUrl: '/spa-the-swan-hotel-spa-holte-spa.jpg',
    keyFeatures: [
      'Spa access varies by room type',
      'Award: Award-winning spa',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Authentic outdoor Finnish sauna' },
      { name: 'Experience Showers', details: 'Multi-sensory shower experience' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Indoor/outdoor swim-through' },
      { name: 'Outdoor Pool', details: 'Swim-through to outdoor' },
      { name: 'Hydrotherapy Pool', details: 'Naturally filtered, minimal chlorine' },
      { name: 'Swim-Through Pool', details: 'Unique indoor-to-outdoor' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: £40 (2 hours)',
      'Pre-booking: Recommended',
      'Age restriction: 18+ (16-17 with parent/guardian)',
      'Spa hours: 10am-4pm spa access',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
      'Parking: Available',
      'Dog-friendly: Check hotel policy',
      'Treatments: TempleSpa',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: false,
    },
  },
  {
    id: 'langdale-hotel-spa-langdale-leisure',
    name: 'Langdale Hotel & Spa (Langdale Leisure)',
    location: 'Ambleside',
    websiteUrl: 'https://langdale.co.uk',
    businessModel: 'hybrid',
    businessModelText: 'Free leisure facilities, premium spa upgrade available',
    imageUrl: '/spa-langdale-hotel-spa-langdale-leisure.jpg',
    keyFeatures: [
      'Free leisure facilities, premium spa upgrade available',
      'Award: Part of Langdale Estate',
      '20m indoor pool',
      'Available via Brimstone treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: '(in leisure)' },
      { name: 'Laconium', details: 'NO ( in Brimstone)' },
      { name: 'Aroma Steam Room', details: 'NO ( in Brimstone)' },
      { name: 'Ice Room', details: 'NO ( in Brimstone)' },
      { name: 'Experience Showers', details: '(Tropical)' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '20m' },
      { name: 'Outdoor Pool', details: 'NO ( in Brimstone)' },
      { name: 'Swim-Through Pool', details: 'NO ( in Brimstone)' },
      { name: 'Hot Tub', details: 'Spa bath' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: Automatic for guests',
      'Age restriction: Family leisure, 18+ for Brimstone',
      'Spa hours: Throughout stay',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
      'Parking: FREE',
      'Dog-friendly: Check policy',
      'Treatments: Via Brimstone Spa (£75 access)',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: true,
      poolOver15m: true,
      thermalSuite: true,
    },
  },
  {
    id: 'the-wordsworth-hotel-spa',
    name: 'The Wordsworth Hotel & Spa',
    location: 'Grasmere',
    websiteUrl: 'https://Check booking sites',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with all room bookings',
    imageUrl: '/spa-the-wordsworth-hotel-spa.jpg',
    keyFeatures: [
      'Spa included with all room bookings',
      'Award: 4-star, 2 AA Rosettes restaurant',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Heated' },
      { name: 'Hot Tub', details: 'Hot tub or jacuzzi' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: For treatments',
      'Age restriction: Adults only for spa',
      'Spa hours: Guest access throughout stay',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
      'Parking: Available',
      'Dog-friendly: Family-friendly hotel',
      'Treatments: Ytsara Spa products (recently changed from Voya)',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: false,
    },
  },
  {
    id: 'macdonald-old-england-hotel-spa',
    name: 'Macdonald Old England Hotel & Spa',
    location: 'Bowness-on-Windermere',
    websiteUrl: 'https://macdonaldhotels.co.uk',
    businessModel: 'paid-extra',
    businessModelText: 'Spa costs extra: NOT included - pay separately',
    imageUrl: '/spa-macdonald-old-england-hotel-spa.jpg',
    keyFeatures: [
      'Spa costs extra: NOT included - pay separately',
      'Award: Established hotel',
      '20m pool',
      '8 rooms treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
      { name: 'Aroma Steam Room', details: 'Aromatherapy steam room' },
      { name: 'Ice Room', details: 'Cool down experience' },
      { name: 'Experience Showers', details: 'Aromatherapy shower' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: '20m with lake views' },
    ],
    accessPolicy: [
      'Hotel guest access: Must book separately/pay extra',
      'Day passes: Various packages',
      'Pre-booking: Recommended',
      'Age restriction: 18+ for treatments, kids allowed in pool',
      'Spa hours: Pool & gym 7am-6:30pm, children swim 10am-5pm',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
      'Parking: £20/night',
      'Dog-friendly: £20/night (one per room, limited rooms)',
      'Treatments: Elemis (signature), Jennifer Young',
    ],
    facilities: {
      sauna: true,
      steamRoom: true,
      iceRoom: true,
      hotTub: false,
      poolOver15m: true,
      thermalSuite: true,
    },
  },
  {
    id: 'the-spa-at-low-wood-bay',
    name: 'The Spa at Low Wood Bay',
    location: 'Windermere',
    websiteUrl: 'https://englishlakes.co.uk/low-wood-bay/spa',
    businessModel: 'day-passes',
    businessModelText: 'Spa access varies by room type',
    imageUrl: '/spa-the-spa-at-low-wood-bay.jpg',
    keyFeatures: [
      'Spa access varies by room type',
      'Award: Best Spa North West 2025, 5 Bubble Luxury Spa',
      'Multiple treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Fellside Sauna panoramic views' },
      { name: 'Herbal Lounge', details: 'The Herbal Lounge' },
      { name: 'Experience Showers', details: 'Multi-sensory shower experience' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Thermal & vitality pool' },
      { name: 'Outdoor Pool', details: '2x heated infinity pools' },
      { name: 'Vitality Pool', details: 'Indoor' },
      { name: 'Hot Tub', details: 'Multiple outdoor hot tubs' },
    ],
    accessPolicy: [
      'Hotel guests: 25% OFF treatments Mon-Thu only',
      'Pre-booking: advance booking recommended',
      'Age restriction: 16+ only',
      'Spa hours: Sunrise 7:30am-9:30am, Treatments 9:30am-7:30pm, Spa Days 10am-8pm',
    ],
    goodToKnow: [
      'What to bring: Own flip flops (sustainable policy)',
      'Parking: Available',
      'Dog-friendly: Check policy',
      'Treatments: Berry & Birch signature + ESPA',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: false,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  },
  {
    id: 'ambleside-salutation-hotel-spa-waterfall-spa',
    name: 'Ambleside Salutation Hotel & Spa (Waterfall Spa)',
    location: 'Ambleside',
    websiteUrl: 'https://hotelslakedistrict.com',
    businessModel: 'free-with-booking',
    businessModelText: 'Spa included with all room bookings',
    imageUrl: '/spa-ambleside-salutation-hotel-spa-waterfall-spa.jpg',
    keyFeatures: [
      'Spa included with all room bookings',
      'Award: BW Premier Collection, WorldHotels Distinctive',
      'Multiple treatment rooms',
    ],
    thermalFacilities: [
      { name: 'Finnish Sauna', details: 'Traditional Finnish sauna' },
      { name: 'Ice Room', details: 'Ice fountain' },
    ],
    poolFeatures: [
      { name: 'Indoor Pool', details: 'Heated' },
      { name: 'Outdoor Pool', details: 'Outdoor fountain spa' },
      { name: 'Hot Tub', details: '2x spa tubs/hot tubs' },
    ],
    accessPolicy: [
      'Spa included with room booking',
      'Day passes: Not available',
      'Pre-booking: For treatments',
      'Age restriction: Adults only for spa',
      'Spa hours: Throughout guest stay',
    ],
    goodToKnow: [
      'What to bring: Swimming attire',
      'Parking: FREE on-site',
      'Dog-friendly: YES - Dog-friendly rooms',
      'Treatments: Elemis Waterfall Spa (some sources mention Clarins)',
    ],
    facilities: {
      sauna: true,
      steamRoom: false,
      iceRoom: true,
      hotTub: true,
      poolOver15m: false,
      thermalSuite: true,
    },
  }
];

export const locations = [
  'All Locations',
  'Ambleside',
  'Bassenthwaite',
  'Borrowdale',
  'Bowness-on-Windermere',
  'Grasmere',
  'Great Langdale',
  'Newby Bridge',
  'Windermere'
];

export const facilityOptions = [
  { key: 'sauna', label: 'Sauna' },
  { key: 'steamRoom', label: 'Steam Room' },
  { key: 'iceRoom', label: 'Ice Room' },
  { key: 'hotTub', label: 'Hot Tub' },
  { key: 'poolOver15m', label: 'Pool 15m+' },
  { key: 'thermalSuite', label: 'Thermal Suite' },
] as const;

